import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'
import { useState } from 'react'
import Header from './components/Header'
import Footer from './components/Footer'
import Home from './components/Home'
import Search from './components/Search'
import AllCareers from './components/AllCareers'
import FilteredCareers from './components/FilteredCareers'
import CareerDetail from './components/CareerDetail'
import Contacts from './components/Contacts'